site_name: 'ba.gov.br Docs'
site_description: 'ba.gov.br Docs'
#site_author: cmvaz
#site_url: gitlab.com 

#Repository
#repo_name: 
#repo_url: 


theme:
  palette:
    primary: blue 
    accent: deep-grey
  name: material
  language: 'pt'
  favicon: favicon.ico
  logo: 
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.expand   
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate

nav:
 - Home : index.md
 - Devs: 
    - Vis√£o Geral: devs.md
    - RespBuilder: respbuilder.md 
 - POs: po.md 
 - QAs: qa.md
 - Devops: devops.md 
 
markdown_extensions:
 - toc:
     permalink: true
     title: On this page
 - pymdownx.tasklist:
     custom_checkbox: true
     clickable_checkbox: false
 - admonition
 - pymdownx.details
 - pymdownx.superfences
 - pymdownx.snippets

extra:
  social:
    # - icon: material/email
    #  link: mailto:
    #  name: 
    # - icon: material/slack
    #  link: 
    #  name: 
    # - icon: material/microsoft-teams
    #  name: 
    # - icon: material/microsoft-teams
    #  name: 
